/*
 * Zweck und Abdeckung: Belastet Fachregeln mit widersprüchlichen, mehrdeutigen
 * und unvollständigen Eingaben. Im Mittelpunkt stehen konservative Status- und
 * Prüfbedarfsableitungen statt der üblichen Positivfälle.
 * Abgrenzung: Keine Browser-, PDF- oder vollständige Berichtslayoutprüfung.
 */
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const elements=new Map();
function element(selector=''){
  if(!elements.has(selector))elements.set(selector,{textContent:'',innerHTML:'',hidden:false,disabled:false,style:{},dataset:{},tagName:'DIV',addEventListener(){},querySelector(){return null;},querySelectorAll(){return[];},scrollIntoView(){}});
  return elements.get(selector);
}
const storage=new Map(),windowObject={location:{search:''},scrollTo(){},print(){}};
const context=vm.createContext({console,structuredClone,URLSearchParams,window:windowObject,confirm:()=>true,localStorage:{getItem:key=>storage.has(key)?storage.get(key):null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)},document:{querySelector:element,querySelectorAll:()=>[]}});
windowObject.window=windowObject;
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','guide-reference.js'),'utf8'),context,{filename:'guide-reference.js'});
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8'),context,{filename:'app.js'});

const results=vm.runInContext(`(() => {
  const out=[];
  const test=(name,fn)=>{try{const pass=Boolean(fn());out.push({name,pass,detail:pass?'OK':'Erwartung nicht erfüllt'});}catch(error){out.push({name,pass:false,detail:error.stack||error.message});}};
  const risk=(overrides={})=>({riskId:'R-X',currentRisk:'high',acceptance:'notAccepted',treatmentNeeded:'yes',suitableTreatmentAvailability:'available',treatmentStatus:'planned',expectedResidual:'low',...overrides});
  const annex=(area='annexEmployment')=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{assessmentDate:'2028-09-30',role_provider:true,roleProviderFact:'yes',role_deployer:true,roleDeployerFact:'yes',[area]:'yes',specificAnnexUse:'Dokumentierter Anhang-III-Fall',narrowProcedural:'no',completedResultImprovement:'no',patternDetection:'no',preparatoryTask:'no',materialInfluenceControl:'no',profiling:'no',annexHighRiskConclusion:'yes',annexBasis:'Belegt',annexEvidence:'Nachweis',publicServiceEntity:'no',unionAuthority:'no',timeTransition:'no',timeLawChanged:'no'});return s;};
  const product=()=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{assessmentDate:'2029-01-01',role_provider:true,roleProviderFact:'yes',productCovered:'yes',productSafetyComponent:'yes',annexISection:'A',thirdPartyConformity:'yes',conformityNonSafetyOnly:'no',productHighRiskConclusion:'yes',productHighRiskBasis:'Belegt',productHighRiskEvidence:'Nachweis',timeTransition:'no',timeLawChanged:'no'});return s;};
  const gpai=overrides=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{gModel:'yes',gIndicativeFlops:'no',gResearchOnly:'no',gObjectType:'model',gSelfProvision:'yes',gModification:'no',gNonEuProvider:'no',gOpenSource:'no',gSystemicRisk:'no',gCommissionDesignation:'no',gAnnexXIII:'no',gpaiOrganizationRole:'provider',gpaiConclusion:'model',gpaiBasis:'Belegt',gpaiEvidence:'Nachweis'},overrides);return s;};
  const cra=overrides=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{craDigitalProduct:'yes',craRemoteProcessing:'no',craDataConnection:'yes',craCommercial:'yes',craPrototype:'no',craOpenSource:'no',craExclusion:'no',craRole:'none',craRoleManufacturer:'no',craRoleRepresentative:'no',craRoleImporter:'no',craRoleDistributor:'no',craRoleSteward:'no',craSubstantialChange:'no',craManufacturerTakeover:'no',craProductClass:'other',craAiActOverlap:'no',craProductType:'software',craProductRelation:'standalone',craConformityProcedure:'Dokumentiert',craVulnerabilityProcess:'Dokumentiert',craReportingProcess:'Dokumentiert',craTransitionDates:'Dokumentiert',craConclusion:'product_only',craBasis:'Belegt',craEvidence:'Nachweis'},overrides);return s;};

  test('REVIEW-10 geplant: hohes erwartetes Restrisiko schlägt alten niedrigen Verifikationswert',()=>withTemporaryState(fillRegulatoryNo(freshState()),()=>{state.risks=[risk({expectedResidual:'high',verifiedResidual:'low'})];return evaluateReview10().value==='yes'&&review10RiskState(state.risks[0]).source==='erwartetes Restrisiko';}));
  test('REVIEW-10 geplant: niedriges erwartetes Restrisiko ignoriert alten hohen Verifikationswert',()=>withTemporaryState(fillRegulatoryNo(freshState()),()=>{state.risks=[risk({expectedResidual:'low',verifiedResidual:'high'})];return evaluateReview10().value==='no'&&review10RiskState(state.risks[0]).level==='low';}));
  test('REVIEW-10 umgesetzt aber nicht verifiziert bleibt Prüfbedarf',()=>withTemporaryState(fillRegulatoryNo(freshState()),()=>{state.risks=[risk({treatmentStatus:'implemented',verifiedResidual:'low'})];return evaluateReview10().value==='review'&&review10RiskState(state.risks[0]).level==='unknown';}));
  for(const [level,expected] of [['low','no'],['medium','no'],['high','yes']])test('REVIEW-10 verifiziertes Restrisiko '+level,()=>withTemporaryState(fillRegulatoryNo(freshState()),()=>{state.risks=[risk({treatmentStatus:'verified',verifiedResidual:level})];return evaluateReview10().value===expected;}));
  test('Rückwechsel von verifiziert zu geplant verwendet wieder ausschließlich den Erwartungswert',()=>withTemporaryState(fillRegulatoryNo(freshState()),()=>{const r=risk({treatmentStatus:'verified',verifiedResidual:'high',expectedResidual:'low'});state.risks=[r];r.treatmentStatus='planned';return evaluateReview10().value==='no'&&review10RiskState(r).level==='low';}));

  test('DUTY-16 besitzt einen eigenen erreichbaren Abschnitt-5-Zeitpfad',()=>{const s=annex();Object.assign(s.form,{annexHighRiskConclusion:'exception',narrowProcedural:'yes',materialInfluenceControl:'no',profiling:'no'});return withTemporaryState(s,()=>{const d=requiredHighRiskDuties().find(item=>item.code==='DUTY-16'),t=dutyTemporalMeta(d);return t.applicableDate==='2026-08-02'&&t.applicability==='current'&&t.applicabilityReason.includes('Art. 6 Abs. 4');});});
  test('DUTY-15 des ursprünglichen Anbieters folgt dem konkreten Hochrisiko-Zeitpfad und nicht Abschnitt 5',()=>withTemporaryState(product(),()=>{const d=requiredHighRiskDuties().find(item=>item.code==='DUTY-15'),t=dutyTemporalMeta(d);return d&&d.art25RoleTakeover===false&&t.applicableDate==='2028-08-02'&&t.applicabilityReason.includes('konkreten Hochrisiko-Zeitpfad');}));
  test('Anhang-III-Pflichten verwenden den 2. Dezember 2027',()=>withTemporaryState(annex(),()=>dutyTemporalMeta(requiredHighRiskDuties().find(item=>item.code==='DUTY-02')).applicableDate==='2027-12-02'));
  test('Anhang-I-Pflichten verwenden den 2. August 2028',()=>withTemporaryState(product(),()=>dutyTemporalMeta(requiredHighRiskDuties().find(item=>item.code==='DUTY-02')).applicableDate==='2028-08-02'));
  test('Gleichzeitige Anhang-I- und Anhang-III-Pfade bleiben beide sichtbar',()=>{const s=annex();Object.assign(s.form,{productCovered:'yes',productSafetyComponent:'yes',thirdPartyConformity:'yes',conformityNonSafetyOnly:'no',productHighRiskConclusion:'yes',productHighRiskBasis:'Belegt',productHighRiskEvidence:'Nachweis'});return withTemporaryState(s,()=>{const t=dutyTemporalMeta(requiredHighRiskDuties().find(item=>item.code==='DUTY-02'));return t.temporalPaths?.length===2&&t.temporalPaths.some(p=>p.applicableDate==='2027-12-02')&&t.temporalPaths.some(p=>p.applicableDate==='2028-08-02');});});
  test('DUTY-12 registriert nicht pauschal produktbezogene Hochrisikofälle',()=>withTemporaryState(product(),()=>requiredHighRiskDuties().find(item=>item.code==='DUTY-12')?.registrationStatus==='no'));
  test('DUTY-20 behält Art.-26-Zeitstatus trotz ungeklärter Registrierung',()=>{const s=annex();Object.assign(s.form,{unionAuthority:'review',highRiskTemporalStatus:'current',highRiskTemporalReason:'Hochrisiko-Hauptpflicht ist anwendbar.',highRiskApplicableDate:'2027-12-02'});return withTemporaryState(s,()=>{const d=requiredHighRiskDuties().find(item=>item.code==='DUTY-20'),t=dutyTemporalMeta(d);return d.registrationStatus==='review'&&t.applicability!=='not_assessable'&&d.subRequirements.length===2;});});

  test('Privates Beschäftigungssystem erzeugt ohne CTX-13 keine DUTY-21',()=>withTemporaryState(annex('annexEmployment'),()=>!requiredHighRiskDuties().some(item=>item.code==='DUTY-21')));
  test('Öffentliche Stelle erzeugt DUTY-21 über CTX-13',()=>{const s=annex('annexEducation');s.form.publicServiceEntity='yes';return withTemporaryState(s,()=>requiredHighRiskDuties().find(item=>item.code==='DUTY-21')?.applicabilityDecision==='yes');});
  test('Anhang III Nr. 5 b/c erzeugt DUTY-21 über HR-20',()=>{const s=annex('annexEssentialServices');s.form.annexIII5bc='yes';return withTemporaryState(s,()=>requiredHighRiskDuties().find(item=>item.code==='DUTY-21')?.hr20Relevant===true);});
  test('Anhang III Nr. 2 allein schließt DUTY-21 aus',()=>withTemporaryState(annex('annexCriticalInfrastructure'),()=>!requiredHighRiskDuties().some(item=>item.code==='DUTY-21')));
  test('Anhang III Nr. 2 schließt weitere dokumentierte Bereiche nicht pauschal aus',()=>{const s=annex('annexCriticalInfrastructure');Object.assign(s.form,{annexEmployment:'yes',publicServiceEntity:'yes'});return withTemporaryState(s,()=>requiredHighRiskDuties().some(item=>item.code==='DUTY-21'));});

  test('GPAI-Forschung und Marktbereitstellung erzeugen einen Widerspruch',()=>withTemporaryState(gpai({gResearchOnly:'yes',gSelfProvision:'yes',gpaiConclusion:'research_exception'}),()=>evaluateGPAI().code==='review'&&evaluateGPAI().contradictions.some(text=>text.includes('Marktbereitstellung'))));
  test('Systemisches Risiko ohne GPAI-Modell erzeugt Prüfbedarf',()=>withTemporaryState(gpai({gModel:'no',gSystemicRisk:'yes',gpaiConclusion:'systemic'}),()=>evaluateGPAI().code==='review'));
  test('Kommissionsbenennung ohne GPAI-Modell erzeugt Prüfbedarf',()=>withTemporaryState(gpai({gModel:'no',gCommissionDesignation:'yes',gpaiConclusion:'systemic'}),()=>evaluateGPAI().code==='review'));
  test('Integration ohne Modellkomponente erzeugt Prüfbedarf',()=>withTemporaryState(gpai({gModel:'no',gObjectType:'integrating',gSelfProvision:'no',gpaiOrganizationRole:'integrator',gpaiConclusion:'integration'}),()=>evaluateGPAI().code==='review'));
  test('Nicht systemisches Open-Source-GPAI aus Drittland erzeugt nicht DUTY-29',()=>withTemporaryState(gpai({gOpenSource:'yes',gNonEuProvider:'yes'}),()=>!requiredHighRiskDuties().some(item=>item.code==='DUTY-29')));

  test('Unvollständig belegter CRA-Prototyp bleibt Prüfbedarf',()=>withTemporaryState(cra({craPrototype:'yes',craPrototypeLimitedTesting:'review',craPrototypeMarked:'yes',craConclusion:'review'}),()=>evaluateCRA().code==='review'));
  test('Ohne nachgewiesene Prototyp-Sonderregelung bleiben Herstellerpflichten ableitbar',()=>withTemporaryState(cra({craPrototype:'no',craRole:'manufacturer',craRoleManufacturer:'yes',craConclusion:'yes'}),()=>['DUTY-32','DUTY-33','DUTY-34','DUTY-35'].every(id=>requiredHighRiskDuties().some(item=>item.code===id))));
  test('CRA-Mehrfachrollen leiten nur die ausgewählten Rollen ab',()=>withTemporaryState(cra({craRole:'multiple',craRoleManufacturer:'yes',craRoleImporter:'yes',craConclusion:'yes'}),()=>{const e=evaluateCRA(),ids=requiredHighRiskDuties().map(item=>item.code);return e.roles.length===2&&e.roles.includes('Hersteller')&&e.roles.includes('Einführer')&&!e.roles.includes('Händler')&&ids.includes('DUTY-32')&&ids.includes('DUTY-36');}));

  test('Nicht anwendbare Pflicht verschlechtert weder Status noch REVIEW-12 oder REVIEW-40',()=>{const s=exampleState();return withTemporaryState(s,()=>{syncDerivedRegisters();const before=overallDecision(false,true).code;state.registers.regulatory.push({id:'REG-NA',sourceQuestionId:'TIME-01',dutyCode:'DUTY-02',basis:'Art. 9',requirement:'Nicht einschlägig',linkedResult:'Dokumentierte Nichtanwendung',obligatedRole:'Anbieter',applicability:'not_applicable',applicabilityReason:'Tatbestand nicht erfüllt'});return overallDecision(false,true).code===before&&!reviewOperationalResult('REVIEW-12').reason.includes('7 offene')&&!reviewOperationalResult('REVIEW-40').value.includes('Regulatorische Pflichten: 1')&&!incompleteRegisterItems().some(text=>text.includes('REG-NA'));});});
  test('Automatischer PB-Eintrag wird bei weiterhin offener Quelle erneut geöffnet',()=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{legalRegimeFulfilment:'unresolved',legalRegimeFulfilmentEvidence:'Ungeklärt'});return withTemporaryState(s,()=>{syncDerivedRegisters();const pb=activeRegisterItems('legal').find(item=>item.id==='PB-DUTY-47');pb.status='resolved';syncDerivedRegisters();return pb.status==='open'&&pb.syncConflictEvidence.includes('weiterhin ungeklärt');});});
  test('Manueller Eintrag mit gleicher ID bleibt manuell und beim Quellwegfall aktiv',()=>{const s=fillRegulatoryNo(freshState());return withTemporaryState(s,()=>{const manual=state.registers.regulatory.find(item=>item.id==='REG-DUTY-01');syncDerivedRegisters();state.form.role_deployer=false;state.form.role_provider=false;syncDerivedRegisters();return manual.derived!==true&&manual.sourceActive!==false;});});
  test('Dubletten-Konfliktnachweis wird validiert und im Bericht angezeigt',()=>{const s=exampleState();s.registers.regulatory.push({...s.registers.regulatory[0],owner:'Abweichende Stelle'});return withTemporaryState(s,()=>{syncDerivedRegisters();const issue=registerValidation().issues.some(text=>text.includes('Synchronisierungskonflikt')),report=buildReport(buildReportData());return issue&&report.includes('Synchronisierungskonflikt')&&report.includes('erhaltener Wert');});});

  test('Alle vier Bewertungsstatus besitzen die richtige Berichtsart',()=>{const base=fillRegulatoryNo(freshState());base.risks=[{riskId:'R-STABIL',probability:'1',impact:'1',acceptance:'accepted',treatmentNeeded:'no',acceptanceReason:'Niedriges Risiko.',riskOwner:'Fachbereich',acceptanceApproval:'Dokumentierte Akzeptanz.'}];const conditionalState=structuredClone(base);conditionalState.registers.legal=[{id:'PB-OFFEN',sourceQuestionId:'REVIEW-07',question:'Nicht blockierender Prüfbedarf',reason:'Klärung offen',linkedResult:'Vergleichsfall',owner:'Fachstelle',due:'2027-01-01',status:'open',blocking:'no'}];const conditional=withTemporaryState(conditionalState,()=>reportCompletionStatus());const final=withTemporaryState(base,()=>reportCompletionStatus());const draft=withTemporaryState(freshState(),()=>reportCompletionStatus());const stopped=structuredClone(base);Object.assign(stopped.form,{pManipulation:'confirmed',pManipulationUse:'Dokumentiert',pManipulationElementsResult:'met',pManipulationElements:'Tatbestand erfüllt',pManipulationException:'none',pManipulationReason:'Belegt',pManipulationEvidence:'Nachweis',pManipulationAffected:'Betroffene',pManipulationLegalOwner:'Rechtsstelle',pManipulationCritical:'yes',prohibitionConclusion:'confirmed'});const negative=withTemporaryState(stopped,()=>reportCompletionStatus());return conditional.status==='conditional'&&final.status==='final'&&draft.status==='draft'&&negative.status==='final'&&negative.decision.code==='USE_NOT_CONTINUABLE';});
  test('Sichtbarer Bericht enthält keine bekannten internen Ergebnis- oder Statuscodes',()=>withTemporaryState(exampleState(),()=>{const text=buildReport(buildReportData()).replace(/<[^>]+>/g,' ').replace(/\\s+/g,' '),codes=[' none ',' provider ',' deployer ',' multiple ',' not_continued ',' not_met ',' possible ',' confirmed ',' exception_confirmed ',' exception_review ','ASSESSMENT_COMPLETE','ASSESSMENT_COMPLETE_WITH_OPEN_MEASURES','ASSESSMENT_NOT_CONCLUDABLE','USE_NOT_CONTINUABLE','product_only','not_applicable','not_assessable','inReview','notFulfilled'];return codes.every(code=>!text.includes(code));}));
  test('Bericht verwendet logische Kapitel statt falscher physischer Seitenzahl',()=>withTemporaryState(exampleState(),()=>{const report=buildReport(buildReportData());return report.includes('Berichtskapitel 1 von 15')&&report.includes('Kapitel 15 / 15')&&!report.includes('Seite 1 von 15');}));

  test('Beschädigter aktueller Speicher fällt auf gültigen Version-10-Stand zurück',()=>{const keys=[STORAGE_KEY,LEGACY_V10_KEY];keys.forEach(key=>localStorage.removeItem(key));localStorage.setItem(STORAGE_KEY,'{beschädigt');localStorage.setItem(LEGACY_V10_KEY,JSON.stringify({schemaVersion:10,form:{toolName:'Wiederhergestellt',craRole:'none'},evaluated:Array(8).fill(true),risks:[],org:{},registers:{regulatory:[],risk:[],organizational:[],expert:[],legal:[]},triggers:[]}));const loaded=loadState(),ok=loaded.form.toolName==='Wiederhergestellt'&&loaded.schemaVersion===14&&loaded.migration.auditTrail.some(entry=>entry.recovery===true)&&loaded.evaluated.every(value=>value===false);keys.forEach(key=>localStorage.removeItem(key));return ok;});
  test('Unbekannte Organisations- und Triggerdaten vor Version 6 bleiben erhalten',()=>{const legacy={schemaVersion:5,form:{toolName:'Alt'},evaluated:Array(8).fill(true),risks:[],org:{altBereich:{notiz:'Erhalten'}},registers:{regulatory:[],risk:[],organizational:[],expert:[],legal:[]},triggers:[{id:'altTrigger',reason:'Erhalten'}]};const m=migrateToCurrent(legacy,5);return m.schemaVersion===14&&m.legacyPreV6.org.altBereich.notiz==='Erhalten'&&m.legacyPreV6.triggers[0].id==='altTrigger'&&m.migration.reviewRequired&&m.evaluated[5]===false&&m.evaluated[7]===false;});
  test('Version-1-Risiko erhält Standardname, Owner, Notiz und Originalobjekt',()=>{const legacy={schemaVersion:1,form:{toolName:'Alt'},evaluated:Array(8).fill(true),risks:[{id:'A',name:'Unzutreffende oder nicht belastbare Ausgaben',owner:'Alt-Owner',notes:'Alt-Notiz',custom:'Zusatz',probability:'4',impact:'4'}],org:{},registers:{regulatory:[],risk:[],organizational:[],expert:[],legal:[]},triggers:[]};const m=migrateToCurrent(legacy,1),r=m.risks[0];return r.description==='Unzutreffende oder nicht belastbare Ausgaben'&&r.owner==='Alt-Owner'&&r.notes==='Alt-Notiz'&&r.legacyOriginal.custom==='Zusatz';});
  test('Leitfadenabdeckung umfasst 291 umgesetzte und drei reservierte Kennungen',()=>{const check=validateGuideImplementation();return check.valid&&check.referenceCount===294&&check.implementedCount===294&&GUIDE_REFERENCE.filter(item=>item.reserved).length===3;});
  return out;
})()`,context);

for(const item of results)console.log(`${item.pass?'✓':'✗'} ${item.name}${item.pass?'':` – ${item.detail}`}`);
const passed=results.filter(item=>item.pass).length,failed=results.length-passed;
console.log(`\n${passed} adversariale Randfalltests bestanden, ${failed} fehlgeschlagen`);
process.exitCode=failed?1:0;
