/*
 * Zweck und Abdeckung: Sichert die erste Korrekturrunde zu Leitfadenabdeckung,
 * Sonderregeln des Anwendungsbereichs und zentralen regulatorischen Ergebnissen.
 * Fälle zum Anwendungsbereich prüfen die Wirkung einzelner Sonderregeln ohne Nebenannahmen.
 * Abgrenzung: Ergänzt die Grundsuite gezielt und prüft weder Browser noch PDF-Ausgabe.
 */
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const elements=new Map();
function element(selector=''){
  if(!elements.has(selector))elements.set(selector,{textContent:'',innerHTML:'',hidden:false,disabled:false,style:{},dataset:{},tagName:'DIV',addEventListener(){},querySelector(){return null;},querySelectorAll(){return[];},scrollIntoView(){}});
  return elements.get(selector);
}
const storage=new Map(),windowObject={location:{search:''},scrollTo(){},print(){}};
const context=vm.createContext({console,structuredClone,URLSearchParams,window:windowObject,confirm:()=>true,localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)},document:{querySelector:element,querySelectorAll:()=>[]}});
windowObject.window=windowObject;
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','guide-reference.js'),'utf8'),context,{filename:'guide-reference.js'});
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8'),context,{filename:'app.js'});

const results=vm.runInContext(`(() => {
  const out=[];
  const test=(name,fn)=>{try{const pass=Boolean(fn());out.push({name,pass,detail:pass?'OK':'Erwartung nicht erfüllt'});}catch(error){out.push({name,pass:false,detail:error.stack||error.message});}};
  const result=id=>reviewOperationalResult(id);
  const roleReady=alignment=>{const s=fillRegulatoryNo(freshState());roleQuestionKeys.forEach(key=>s.form[key]='no');Object.assign(s.form,{roleDeployerFact:'yes',role_deployer:true,purposeAlignment:alignment});s.evaluated[2]=true;return s;};
  const annexHigh=()=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{role_deployer:true,roleDeployerFact:'yes',annexEmployment:'yes',annexCriticalInfrastructure:'no',specificAnnexUse:'Personalvorauswahl',narrowProcedural:'no',completedResultImprovement:'no',patternDetection:'no',preparatoryTask:'no',materialInfluenceControl:'no',profiling:'no',annexHighRiskConclusion:'yes',annexBasis:'Anhang III ist einschlägig.',annexEvidence:'Nachweis',publicServiceEntity:'no',annexIII5bc:'no',unionAuthority:'no',highRiskTemporalStatus:'current',highRiskTemporalReason:'Am Bewertungsstichtag anwendbar.'});return s;};
  const gpai=overrides=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{gModel:'yes',gIndicativeFlops:'no',gResearchOnly:'no',gObjectType:'model',gSelfProvision:'yes',gModification:'no',gNonEuProvider:'no',gOpenSource:'no',gSystemicRisk:'no',gCommissionDesignation:'no',gAnnexXIII:'no',gpaiOrganizationRole:'provider',gpaiConclusion:'model',gpaiBasis:'Rolle und Modell sind belegt.',gpaiEvidence:'Modellakte',gpaiTemporalStatus:'current',gpaiTemporalReason:'Anwendungszeitpunkt belegt.'},overrides);return s;};
  const cra=overrides=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{craDigitalProduct:'yes',craRemoteProcessing:'no',craDataConnection:'yes',craCommercial:'yes',craPrototype:'no',craOpenSource:'no',craExclusion:'no',craRole:'none',craRoleManufacturer:'no',craRoleRepresentative:'no',craRoleImporter:'no',craRoleDistributor:'no',craRoleSteward:'no',craSubstantialChange:'no',craManufacturerTakeover:'no',craProductClass:'other',craAiActOverlap:'no',craProductType:'software',craProductRelation:'standalone',craConformityProcedure:'Dokumentiert',craVulnerabilityProcess:'Dokumentiert',craReportingProcess:'Dokumentiert',craTransitionDates:'Dokumentiert',craConclusion:'product_only',craBasis:'Begründet',craEvidence:'Nachweis'},overrides);return s;};
  const activeIdUnique=s=>Object.values(s.registers).every(list=>{const ids=list.filter(isActiveRegisterItem).map(item=>item.id).filter(isFilled);return ids.length===new Set(ids).size;});

  for(const alignment of ['partial','substantial','review'])test('CTX-02 '+alignment+' synchronisiert PB, Status und Bericht ohne manuellen Klick',()=>{const s=roleReady(alignment);return withTemporaryState(s,()=>{const decision=overallDecision(false,true),pb=activeRegisterItems('legal').find(item=>item.id==='PB-DUTY-45'),report=buildReport(buildReportData());return Boolean(pb)&&report.includes('PB-DUTY-45')&&decision.code!=='ASSESSMENT_COMPLETE';});});
  for(const value of ['unresolved','review'])test('DUTY-47 '+value+' synchronisiert PB, Status und Bericht ohne manuellen Klick',()=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{legalRegimeFulfilment:value,legalRegimeFulfilmentEvidence:'Rechtsregime wurden geprüft; Klärung bleibt offen.'});return withTemporaryState(s,()=>{const decision=overallDecision(false,true),pb=activeRegisterItems('legal').find(item=>item.id==='PB-DUTY-47'),report=buildReport(buildReportData());return Boolean(pb)&&report.includes('PB-DUTY-47')&&decision.code==='ASSESSMENT_NOT_CONCLUDABLE';});});
  test('Wechsel von CTX-02 partial auf matches deaktiviert den früheren PB automatisch',()=>{const s=roleReady('partial');return withTemporaryState(s,()=>{overallDecision(false,true);state.form.purposeAlignment='matches';overallDecision(false,true);const item=state.registers.legal.find(entry=>entry.originalId==='PB-DUTY-45'||entry.id==='PB-DUTY-45');return item?.sourceActive===false&&!activeRegisterItems('legal').some(entry=>entry.id==='PB-DUTY-45');});});
  test('Wechsel von DUTY-47 unresolved auf clarified deaktiviert den früheren PB automatisch',()=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{legalRegimeFulfilment:'unresolved',legalRegimeFulfilmentEvidence:'Ungeklärt.'});return withTemporaryState(s,()=>{overallDecision(false,true);state.form.legalRegimeFulfilment='clarified';state.form.legalRegimeFulfilmentEvidence='Eindeutig geklärt und belegt.';overallDecision(false,true);return !activeRegisterItems('legal').some(entry=>entry.id==='PB-DUTY-47')&&state.registers.legal.some(entry=>entry.id==='PB-DUTY-47'&&entry.sourceActive===false);});});
  test('Musterfall enthält nach der ersten Synchronisierung keine doppelten aktiven IDs und bleibt bei Widersprüchen offen',()=>{const s=exampleState();return withTemporaryState(s,()=>{syncDerivedRegisters();return activeIdUnique(state)&&overallDecision().code==='ASSESSMENT_NOT_CONCLUDABLE';});});
  test('Manueller Eintrag mit gleicher Ziel-ID wird erhalten und nicht dupliziert',()=>{const s=fillRegulatoryNo(freshState());s.registers.regulatory[0].owner='Manuell gepflegte Stelle';return withTemporaryState(s,()=>{syncDerivedRegisters();const items=activeRegisterItems('regulatory').filter(item=>item.id==='REG-DUTY-01');return items.length===1&&items[0].owner==='Manuell gepflegte Stelle';});});
  test('Mehrfaches Synchronisieren ist idempotent',()=>{const s=exampleState();return withTemporaryState(s,()=>{syncDerivedRegisters();const once=Object.values(state.registers).flat().length;for(let i=0;i<5;i++)syncDerivedRegisters();return Object.values(state.registers).flat().length===once&&activeIdUnique(state);});});

  test('Offene erfüllbare Vor-Nutzungs-Pflicht ist REVIEW-09 Nein und offene Maßnahme',()=>{const s=fillRegulatoryNo(freshState()),entry=s.registers.regulatory[0];s.risks=[{riskId:'R-STABIL',probability:'1',impact:'1',acceptance:'accepted',treatmentNeeded:'no',acceptanceReason:'Niedriges Risiko.',riskOwner:'Fachbereich',acceptanceApproval:'Dokumentierte Akzeptanz.'}];Object.assign(entry,{status:'open',beforeRelease:'yes',fulfillability:'fulfillable',fulfillabilityReason:'Umsetzung ist terminiert und möglich.',owner:'Compliance',due:'2027-01-01',evidence:'Umsetzungsplan'});return withTemporaryState(s,()=>result('REVIEW-09').value==='no'&&overallDecision(false,true).code==='ASSESSMENT_COMPLETE_WITH_OPEN_MEASURES');});
  test('Nachweislich nicht erfüllbare Pflicht ist REVIEW-09 Ja und Hindernis',()=>{const s=fillRegulatoryNo(freshState()),entry=s.registers.regulatory[0];Object.assign(entry,{status:'open',fulfillability:'unfulfillable',fulfillabilityReason:'Technisch und organisatorisch nachweislich unmöglich.'});return withTemporaryState(s,()=>result('REVIEW-09').value==='yes'&&overallDecision(false,true).code==='USE_NOT_CONTINUABLE');});
  test('Ungeklärte Erfüllbarkeit erzeugt weiteren Prüfbedarf',()=>{const s=fillRegulatoryNo(freshState()),entry=s.registers.regulatory[0];Object.assign(entry,{status:'open',fulfillability:'not_assessable',fulfillabilityReason:'Klärung offen.'});return withTemporaryState(s,()=>result('REVIEW-09').value==='review'&&overallDecision(false,true).code==='ASSESSMENT_NOT_CONCLUDABLE');});

  test('Hohes erwartetes Restrisiko bleibt trotz verfügbarer Behandlung REVIEW-10 Ja',()=>{const s=fillRegulatoryNo(freshState());s.risks=[{riskId:'R-E',currentRisk:'high',acceptance:'notAccepted',treatmentNeeded:'yes',expectedResidual:'high',treatmentStatus:'planned',suitableTreatmentAvailability:'available'}];return withTemporaryState(s,()=>evaluateReview10().value==='yes'&&overallDecision(false,true).code==='USE_NOT_CONTINUABLE');});
  test('Hohes verifiziertes Restrisiko bleibt trotz verfügbarer Behandlung REVIEW-10 Ja',()=>{const s=fillRegulatoryNo(freshState());s.risks=[{riskId:'R-V',currentRisk:'medium',acceptance:'notAccepted',treatmentNeeded:'yes',expectedResidual:'low',verifiedResidual:'high',treatmentStatus:'verified',suitableTreatmentAvailability:'available'}];return withTemporaryState(s,()=>evaluateReview10().value==='yes');});
  test('Verfügbare Behandlung mit unbestimmtem Restrisiko ist REVIEW-10 Prüfbedarf',()=>{const s=fillRegulatoryNo(freshState());s.risks=[{riskId:'R-U',currentRisk:'high',acceptance:'notAccepted',treatmentNeeded:'yes',expectedResidual:'unknown',treatmentStatus:'planned',suitableTreatmentAvailability:'available'}];return withTemporaryState(s,()=>evaluateReview10().value==='review');});

  test('GPAI-Forschungsausnahme verhindert Anbieterpflichten nur ohne Marktbereitstellung',()=>{const s=gpai({gResearchOnly:'yes',gSelfProvision:'no',gpaiConclusion:'research_exception'});return withTemporaryState(s,()=>evaluateGPAI().code==='research_exception'&&!requiredHighRiskDuties().some(item=>/^DUTY-(27|28|29|30|31)$/.test(item.code)));});
  test('Bloße GPAI-Integration erzeugt keine Anbieterpflichten',()=>{const s=gpai({gObjectType:'integrating',gSelfProvision:'no',gpaiOrganizationRole:'integrator',gpaiConclusion:'integration'});return withTemporaryState(s,()=>evaluateGPAI().code==='integration'&&!requiredHighRiskDuties().some(item=>/^DUTY-(27|28|29|30|31)$/.test(item.code)));});
  test('GPAI-Open-Source-Ausnahme unterdrückt DUTY-27, nicht DUTY-28',()=>{const s=gpai({gOpenSource:'yes'});return withTemporaryState(s,()=>{const ids=requiredHighRiskDuties().map(item=>item.code);return !ids.includes('DUTY-27')&&ids.includes('DUTY-28');});});
  test('Systemisches GPAI-Risiko verhindert die Open-Source-Ausnahme',()=>{const s=gpai({gOpenSource:'yes',gSystemicRisk:'yes',gpaiConclusion:'systemic'});return withTemporaryState(s,()=>{const ids=requiredHighRiskDuties().map(item=>item.code);return ids.includes('DUTY-27')&&ids.includes('DUTY-28')&&ids.includes('DUTY-31');});});

  test('CRA-Prototyp wird nur mit belegten Voraussetzungen als Sonderfall ausgewiesen',()=>{const s=cra({craPrototype:'yes',craPrototypeLimitedTesting:'yes',craPrototypeMarked:'yes',craConclusion:'special'});return withTemporaryState(s,()=>evaluateCRA().code==='special'&&evaluateCRA().specialCase.includes('Prototyp'));});
  test('Nichtkommerzielle Open-Source-Bereitstellung wird als CRA-Sonderfall ausgewiesen',()=>{const s=cra({craCommercial:'no',craOpenSource:'yes',craConclusion:'special'});return withTemporaryState(s,()=>evaluateCRA().code==='special'&&!evaluateCRA().ownObligations);});
  test('CRA-Steward bleibt eigene Rolle und erzeugt DUTY-35',()=>{const s=cra({craCommercial:'no',craOpenSource:'yes',craRole:'steward',craRoleSteward:'yes',craConclusion:'special'});return withTemporaryState(s,()=>evaluateCRA().roles.includes('Open-Source-Software-Steward')&&evaluateCRA().ownObligations&&requiredHighRiskDuties().some(item=>item.code==='DUTY-35'&&item.role.includes('Steward')));});

  test('DUTY-12 wird für die Bevollmächtigtenkonstellation abgeleitet',()=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{role_deployer:false,role_authorisedRepresentative:true,productCovered:'yes',productSafetyComponent:'yes',annexISection:'A',thirdPartyConformity:'yes',conformityNonSafetyOnly:'no',productHighRiskConclusion:'yes',productHighRiskBasis:'Belegt',productHighRiskEvidence:'Nachweis'});return withTemporaryState(s,()=>requiredHighRiskDuties().some(item=>item.code==='DUTY-12'&&item.role.includes('Bevollmächtigter')));});
  test('DUTY-20-Registrierung setzt Anhang III außer Nr. 2 und CTX-14 Ja voraus; weitere Bereiche bleiben erhalten',()=>{const s=annexHigh();return withTemporaryState(s,()=>{state.form.unionAuthority='yes';const yes=requiredHighRiskDuties().find(item=>item.code==='DUTY-20')?.registrationStatus;state.form.annexCriticalInfrastructure='yes';const stillYes=requiredHighRiskDuties().find(item=>item.code==='DUTY-20')?.registrationStatus;state.form.annexEmployment='no';const no=requiredHighRiskDuties().find(item=>item.code==='DUTY-20')?.registrationStatus;return yes==='yes'&&stillYes==='yes'&&no==='no';});});
  test('CTX-13 und CTX-14 als Prüfbedarf erzeugen keine definitive Pflichtenentscheidung',()=>{const s=annexHigh();Object.assign(s.form,{unionAuthority:'review',publicServiceEntity:'review',annexIII5bc:'no'});return withTemporaryState(s,()=>{const duties=requiredHighRiskDuties(),d20=duties.find(item=>item.code==='DUTY-20'),d21=duties.find(item=>item.code==='DUTY-21');return d20?.registrationStatus==='review'&&d21?.applicabilityDecision==='review';});});
  test('DUTY-01 verwendet den eigenständigen Art.-4-Zeitpfad',()=>{const s=fillRegulatoryNo(freshState());s.registers.regulatory=[];Object.assign(s.form,{assessmentDate:'2026-09-30',highRiskTemporalStatus:'future',highRiskTemporalReason:'Hochrisikopfad'});return withTemporaryState(s,()=>{syncDerivedRegisters();const entry=activeRegisterItems('regulatory').find(item=>item.dutyCode==='DUTY-01');return entry?.applicableDate==='2025-02-02'&&entry.applicability==='current'&&entry.applicabilityReason.includes('Art. 4');});});

  test('REVIEW-31 bis REVIEW-40 liefern konkrete Leitfadenwerte und REVIEW-39 nie pauschal Ja',()=>{const s=exampleState();return withTemporaryState(s,()=>{const values=[31,33,37,38,39,40].map(n=>result('REVIEW-'+String(n).padStart(2,'0')).value),criterion=Object.keys(state.org.governance.criteria)[0];Object.assign(state.org.governance.criteria[criterion],{answer:'notFulfilled',reason:'Das Kriterium ist nachweislich nicht erfüllt.'});state.org.governance.status='notFulfilled';const insufficient=result('REVIEW-39').value;return values.every(value=>isFilled(value)&&!['yes','no'].includes(value))&&insufficient==='insufficient';});});
  test('REVIEW-21 prüft Zugriff, gesetzliche und interne Aufbewahrung sowie Altstände',()=>{const s=exampleState();return withTemporaryState(s,()=>{const complete=result('REVIEW-21').value;state.form.statutoryRetentionStatus='review';const open=result('REVIEW-21').value;return complete==='yes'&&open==='review';});});
  test('Reine Leerzeichen gelten nicht als Nachweis, 0 und boolesche Werte bleiben gültig',()=>{const s=fillRegulatoryNo(freshState());Object.assign(s.form,{legalRegimeFulfilment:'clarified',legalRegimeFulfilmentEvidence:' \\t\\n '});return withTemporaryState(s,()=>!isFilled(' \\t\\n ')&&isFilled(0)&&isFilled(false)&&evaluateDutyOperationalResult('DUTY-47').value==='review');});
  test('REVIEW-42 verlangt alle Kategorien, Termin, Frequenz und Begründungen für Nein',()=>{const s=exampleState();return withTemporaryState(s,()=>{const complete=result('REVIEW-42').value;state.triggers[0].required='';const missing=result('REVIEW-42').value;state.triggers[0].required='no';state.triggers[0].reason='';const unreasoned=result('REVIEW-42').value;return complete==='yes'&&missing==='review'&&unreasoned==='review';});});
  test('loadState migriert echte Speicherstände der Versionen 1 bis 11 vollständig und verlustarm',()=>{const keyByVersion={1:LEGACY_V1_KEY,2:LEGACY_V2_KEY,3:LEGACY_V3_KEY,4:LEGACY_V4_KEY,5:LEGACY_V5_KEY,6:LEGACY_V6_KEY,7:LEGACY_V7_KEY,8:LEGACY_V8_KEY,9:LEGACY_V9_KEY,10:LEGACY_V10_KEY,11:LEGACY_V11_KEY},allKeys=[STORAGE_KEY,...Object.values(keyByVersion)];for(let version=1;version<=11;version++){allKeys.forEach(key=>localStorage.removeItem(key));const legacy={schemaVersion:version,form:{toolName:'Alt '+version,legalRegimeFulfilment:version===8?'clarified':'review',craRole:'none'},evaluated:Array(8).fill(true),risks:[{riskId:'ALT',name:'Altrisiko',probability:'4',impact:'4',currentRisk:'critical',owner:'Alt-Owner',notes:'Alt-Notiz'}],org:{},registers:{regulatory:[],risk:[],organizational:[],expert:[],legal:[]},triggers:[],migration:{reviewRequired:true,issues:['Alt-Hinweis']}};localStorage.setItem(keyByVersion[version],JSON.stringify(legacy));const migrated=loadState();if(migrated.schemaVersion!==14||migrated.migration.reviewRequired!==true||migrated.form.toolName!=='Alt '+version||!localStorage.getItem(STORAGE_KEY))return false;if(version<=3&&(migrated.risks[0]?.probability!=='3'||migrated.risks[0]?.currentRisk!=='high'))return false;if(version===1&&(migrated.risks[0]?.owner!=='Alt-Owner'||migrated.risks[0]?.notes!=='Alt-Notiz'||!migrated.risks[0]?.legacyOriginal))return false;if(version===8&&(migrated.form.legalRegimeFulfilment!=='review'||!migrated.legacyDuty47Assessment))return false;if(!migrated.migration.auditTrail?.some(entry=>entry.from===version&&entry.to===(version===1?3:version+1)))return false;if(!migrated.migration.auditTrail?.some(entry=>entry.from===11&&entry.to===12)||!migrated.migration.auditTrail?.some(entry=>entry.from===12&&entry.to===13)||!migrated.migration.auditTrail?.some(entry=>entry.from===13&&entry.to===14))return false;}allKeys.forEach(key=>localStorage.removeItem(key));return true;});
  test('Bericht enthält neue Pflichtabschnitte, konkrete Reviews und ausschließlich eindeutige aktive IDs',()=>{const s=exampleState();return withTemporaryState(s,()=>{const report=buildReport(buildReportData());return activeIdUnique(state)&&['Vollständige Dokumentations- und Reviewangaben','Aufbewahrung und Versionierung','Konkrete Ergebniswerte REVIEW-31 bis REVIEW-40','Neubewertungsauslöser REVIEW-22 bis REVIEW-28','GPAI – Relevanz und Organisationsrolle getrennt'].every(text=>report.includes(text))&&(report.match(/<section class="report-page(?:\\s|")/g)||[]).length===15;});});
  return out;
})()`,context);

for(const item of results)console.log(`${item.pass?'✓':'✗'} ${item.name}${item.pass?'':` – ${item.detail}`}`);
const passed=results.filter(item=>item.pass).length,failed=results.length-passed;
console.log(`\n${passed} Korrekturtests bestanden, ${failed} fehlgeschlagen`);
process.exitCode=failed?1:0;
